python data_hyper_cleaning.py --dynamic_method NGD --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method CG,PTT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method RAD,PTT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method RAD,RGT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method PTT,RAD,RGT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method FD 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method FD,PTT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method NS 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method NS,PTT 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method IGA 
python data_hyper_cleaning.py --dynamic_method NGD --hyper_method IGA,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method CG,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method RAD,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method RAD,RGT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method PTT,RAD,RGT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method FD 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method FD,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method NS 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method NS,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method IGA 
python data_hyper_cleaning.py --dynamic_method DI,NGD --hyper_method IGA,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method CG,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method RAD,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method RAD,RGT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method PTT,RAD,RGT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method FD 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method FD,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method NS 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method NS,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method IGA 
python data_hyper_cleaning.py --dynamic_method GDA,NGD --hyper_method IGA,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method CG,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method RAD,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method RAD,RGT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method PTT,RAD,RGT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method FD 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method FD,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method NS 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method NS,PTT 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method IGA 
python data_hyper_cleaning.py --dynamic_method GDA,NGD,DI --hyper_method IGA,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method CG,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method RAD,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method RAD,RGT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method PTT,RAD,RGT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method FD 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method FD,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method NS 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method NS,PTT 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method IGA 
python data_hyper_cleaning.py --dynamic_method DI,NGD,GDA --hyper_method IGA,PTT 
python data_hyper_cleaning.py --dynamic_method DM --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method DM --hyper_method CG 
python data_hyper_cleaning.py --dynamic_method DM,GDA --hyper_method RAD 
python data_hyper_cleaning.py --dynamic_method DM,GDA --hyper_method CG 
python data_hyper_cleaning.py --fo_gm VSM 
python data_hyper_cleaning.py --fo_gm VFM 
python data_hyper_cleaning.py --fo_gm MESM 
python data_hyper_cleaning.py --fo_gm PGDM 
