python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method CG,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method CG,IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method NS,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method NS,IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method FOA,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD --hyper_method FOA,IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method CG,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method CG,IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method NS,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method NS,IAD,PTT 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method FOA,IAD 
python /home/runner/work/BOAT/BOAT/meta_learning/meta_learning.py --dynamic_method NGD,GDA --hyper_method FOA,IAD,PTT 
