python l2_regularization.py --dynamic_method NGD --hyper_method CG 
python l2_regularization.py --dynamic_method NGD --hyper_method CG,PTT 
python l2_regularization.py --dynamic_method NGD --hyper_method RAD 
python l2_regularization.py --dynamic_method NGD --hyper_method RAD,PTT 
python l2_regularization.py --dynamic_method NGD --hyper_method RAD,RGT 
python l2_regularization.py --dynamic_method NGD --hyper_method PTT,RAD,RGT 
python l2_regularization.py --dynamic_method NGD --hyper_method FD 
python l2_regularization.py --dynamic_method NGD --hyper_method FD,PTT 
python l2_regularization.py --dynamic_method NGD --hyper_method NS 
python l2_regularization.py --dynamic_method NGD --hyper_method NS,PTT 
python l2_regularization.py --dynamic_method NGD --hyper_method IGA 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method CG 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method CG,PTT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method RAD 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method RAD,PTT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method RAD,RGT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method PTT,RAD,RGT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method FD 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method FD,PTT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method NS 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method NS,PTT 
python l2_regularization.py --dynamic_method DI,NGD --hyper_method IGA 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method CG 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method CG,PTT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method RAD 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method RAD,PTT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method RAD,RGT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method PTT,RAD,RGT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method FD 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method FD,PTT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method NS 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method NS,PTT 
python l2_regularization.py --dynamic_method GDA,NGD --hyper_method IGA 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method CG 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method CG,PTT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method RAD 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method RAD,PTT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method RAD,RGT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method PTT,RAD,RGT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method FD 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method FD,PTT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method NS 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method NS,PTT 
python l2_regularization.py --dynamic_method GDA,NGD,DI --hyper_method IGA 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method CG 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method CG,PTT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method RAD 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method RAD,PTT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method RAD,RGT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method PTT,RAD,RGT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method FD 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method FD,PTT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method NS 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method NS,PTT 
python l2_regularization.py --dynamic_method DI,NGD,GDA --hyper_method IGA 
python l2_regularization.py --dynamic_method NGD,DM --hyper_method RAD 
python l2_regularization.py --dynamic_method NGD,DM --hyper_method CG 
python l2_regularization.py --dynamic_method NGD,DM,GDA --hyper_method RAD 
python l2_regularization.py --dynamic_method NGD,DM,GDA --hyper_method CG 
python l2_regularization.py --fo_gm VSM 
python l2_regularization.py --fo_gm VFM 
python l2_regularization.py --fo_gm MESM 
python l2_regularization.py --fo_gm PGDM 
